### ISSUE TITLE
KeyError: 'CameraRGB'

### ISSUE THREAD

**Issue by dingjiangang** [carla-simulator/imitation-learning#10]
when i run "python run_CIL.py",some problem happen
ERROR: 'CameraRGB'
Traceback (most recent call last):
  File "run_CIL.py", line 64, in <module>
    results = corl.benchmark_agent(agent, client)
  File "/home/dingjiangang/carla_env/local/lib/python2.7/site-packages/carla/benchmarks/benchmark.py", line 199, in benchmark_agent
    + '.' + str(end_point))
  File "/home/dingjiangang/carla_env/local/lib/python2.7/site-packages/carla/benchmarks/benchmark.py", line 108, in run_navigation_episode
    control = agent.run_step(measurements, sensor_data, target)
  File "/home/dingjiangang/imitation-learning/agents/imitation/imitation_learning.py", line 95, in run_step
    control = self._compute_action(sensor_data['CameraRGB'].data,
KeyError: 'CameraRGB'

**Comment by marcgpuig** [comment]
Hi @dingjiangang,

Which version of CARLA are you using?
Recently we have made a few changes in the master branch and the code of this repository is temporarily outdated.

Consider using the [stable](https://github.com/carla-simulator/carla/tree/stable) branch of CARLA.
