### ISSUE TITLE
Questions of running run_CIL on Town02

### ISSUE THREAD

**Issue by QD-HK** [carla-simulator/imitation-learning#28]
Hey!

When I run the 'run_CIL.py' of Carla_0.8.2 in Town01, it works good. However when change to Town02, something strange happen:
1. The first episode runs smoothly, but the car **turns** two times in this episode. The start and end pose is (38, 34). According to _CoRL2017_ these pose should be a **straight line**. So what's wrong with the setting?
2. When first episode finish and comes to the second one (start and end pose is (4, 2)), the run_CIL will put the following error and stop running: 

Traceback (most recent call last):
File "run_CIL.py", line 72, in <module>
    args.host, args.port)
File "/CARLA_0.8.2/PythonClient/carla/driving_benchmark/driving_benchmark.py", line 294, in run_driving_benchmark
    benchmark_summary = benchmark.benchmark_agent(experiment_suite, agent, client)
File "/CARLA_0.8.2/PythonClient/carla/driving_benchmark/driving_benchmark.py", line 121, in benchmark_agent
    self._get_shortest_path(positions[start_index], positions[end_index]))
File "/CARLA_0.8.2/PythonClient/carla/driving_benchmark/driving_benchmark.py", line 182, in _get_shortest_path
    end_point.orientation.x, end_point.orientation.y, end_point.orientation.z])
File "/CARLA_0.8.2/PythonClient/carla/planner/planner.py", line 114, in get_shortest_path_distance
    track_target, target_ori)
File "/CARLA_0.8.2/PythonClient/carla/planner/city_track.py", line 91, in compute_route
    route = a_star.solve()
File "/CARLA_0.8.2/PythonClient/carla/planner/astar.py", line 142, in solve
    return self.get_path()
File "/CARLA_0.8.2/PythonClient/carla/planner/astar.py", line 111, in get_path
    path.append((cell.x, cell.y))
AttributeError: 'NoneType' object has no attribute 'x'

So is there are somthing wrong in the code?

Thank you very much!
Dai Qi

**Comment by felipecode** [comment]
Hey daqi,
I know what happened ! 
Your server is running town 01 , and you set town02 for the run_CIL.py like this:

    python run_CIL.py -c Town02

Am I right ?
Make sure your server is running for town 02. 

    ./CarlaUE4.sh /Game/Maps/Town02 -windowed -world-port=2000

We will add the possibility to chose the town from the client, since the way you have to execute this now is quite error prone.

**Comment by QD-HK** [comment]
That's true, Thank you!
