### ISSUE TITLE
problem in starting run_cli.py

### ISSUE THREAD

**Issue by king479** [carla-simulator/imitation-learning#87]
C:\Coursera\CarlaSimulator\PythonClient>python run_CIL.py
2020-09-13 16:23:25.798957: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2020-09-13 16:23:25.799759: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

INFO: listening to server localhost:2000
WARNING:tensorflow:From C:\Coursera\CarlaSimulator\PythonClient\agents\imitation\imitation_learning.py:25: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING: From C:\Coursera\CarlaSimulator\PythonClient\agents\imitation\imitation_learning.py:25: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From C:\Coursera\CarlaSimulator\PythonClient\agents\imitation\imitation_learning.py:36: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING: From C:\Coursera\CarlaSimulator\PythonClient\agents\imitation\imitation_learning.py:36: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2020-09-13 16:23:28.537039: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-09-13 16:23:28.547437: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-09-13 16:23:28.635136: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 1650 major: 7 minor: 5 memoryClockRate(GHz): 1.56
pciBusID: 0000:01:00.0
2020-09-13 16:23:28.636473: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2020-09-13 16:23:28.637438: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cublas64_100.dll'; dlerror: cublas64_100.dll not found
2020-09-13 16:23:28.640221: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cufft64_100.dll'; dlerror: cufft64_100.dll not found
2020-09-13 16:23:28.641125: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'curand64_100.dll'; dlerror: curand64_100.dll not found
2020-09-13 16:23:28.642033: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusolver64_100.dll'; dlerror: cusolver64_100.dll not found
2020-09-13 16:23:28.642972: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusparse64_100.dll'; dlerror: cusparse64_100.dll not found
2020-09-13 16:23:28.643870: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudnn64_7.dll'; dlerror: cudnn64_7.dll not found
2020-09-13 16:23:28.643969: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-09-13 16:23:28.828012: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-13 16:23:28.828186: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2020-09-13 16:23:28.829047: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
WARNING:tensorflow:From C:\Coursera\CarlaSimulator\PythonClient\agents\imitation\imitation_learning.py:39: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING: From C:\Coursera\CarlaSimulator\PythonClient\agents\imitation\imitation_learning.py:39: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

 === Conv 0   :   5 2 32
WARNING:tensorflow:From C:\Coursera\CarlaSimulator\PythonClient\agents\imitation\imitation_learning_network.py:14: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING: From C:\Coursera\CarlaSimulator\PythonClient\agents\imitation\imitation_learning_network.py:14: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

Dropout 0
WARNING:tensorflow:From C:\Coursera\CarlaSimulator\PythonClient\agents\imitation\imitation_learning_network.py:85: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING: From C:\Coursera\CarlaSimulator\PythonClient\agents\imitation\imitation_learning_network.py:85: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Tensor("Network/conv_block0/relu1:0", shape=(?, 42, 98, 32), dtype=float32)
 === Conv 1   :   3 1 32
Dropout 1
Tensor("Network/conv_block1/relu2:0", shape=(?, 40, 96, 32), dtype=float32)
 === Conv 2   :   3 2 64
Dropout 2
Tensor("Network/conv_block2/relu3:0", shape=(?, 19, 47, 64), dtype=float32)
 === Conv 3   :   3 1 64
Dropout 3
Tensor("Network/conv_block3/relu4:0", shape=(?, 17, 45, 64), dtype=float32)
 === Conv 4   :   3 2 128
Dropout 4
Tensor("Network/conv_block4/relu5:0", shape=(?, 8, 22, 128), dtype=float32)
 === Conv 5   :   3 1 128
Dropout 5
Tensor("Network/conv_block5/relu6:0", shape=(?, 6, 20, 128), dtype=float32)
 === Conv 6   :   3 1 256
Dropout 6
Tensor("Network/conv_block6/relu7:0", shape=(?, 4, 18, 256), dtype=float32)
 === Conv 7   :   3 1 256
Dropout 7
Tensor("Network/conv_block7/relu8:0", shape=(?, 2, 16, 256), dtype=float32)
Tensor("Network/reshape:0", shape=(?, 8192), dtype=float32)
 === FC 0   :   512
WARNING:tensorflow:From C:\Coursera\CarlaSimulator\PythonClient\agents\imitation\imitation_learning_network.py:97: The name tf.nn.xw_plus_b is deprecated. Please use tf.compat.v1.nn.xw_plus_b instead.

WARNING: From C:\Coursera\CarlaSimulator\PythonClient\agents\imitation\imitation_learning_network.py:97: The name tf.nn.xw_plus_b is deprecated. Please use tf.compat.v1.nn.xw_plus_b instead.

Dropout 8
Tensor("Network/fc1/relu9:0", shape=(?, 512), dtype=float32)
 === FC 1   :   512
Dropout 9
 === FC 2   :   128
Dropout 10
 === FC 3   :   128
Dropout 11
 === FC 4   :   512
Dropout 12
 === FC 5   :   256
Dropout 13
 === FC 6   :   256
Dropout 14
Tensor("Network/Branch_0/fc7/relu15:0", shape=(?, 256), dtype=float32)
 === FC 8   :   256
Dropout 15
 === FC 9   :   256
Dropout 16
Tensor("Network/Branch_1/fc10/relu17:0", shape=(?, 256), dtype=float32)
 === FC 11   :   256
Dropout 17
 === FC 12   :   256
Dropout 18
Tensor("Network/Branch_2/fc13/relu19:0", shape=(?, 256), dtype=float32)
 === FC 14   :   256
Dropout 19
 === FC 15   :   256
Dropout 20
Tensor("Network/Branch_3/fc16/relu21:0", shape=(?, 256), dtype=float32)
 === FC 17   :   256
Dropout 21
 === FC 18   :   256
Dropout 22
Tensor("Network/Branch_4/fc19/relu23:0", shape=(?, 256), dtype=float32)
WARNING:tensorflow:From C:\Coursera\CarlaSimulator\PythonClient\agents\imitation\imitation_learning.py:65: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

WARNING: From C:\Coursera\CarlaSimulator\PythonClient\agents\imitation\imitation_learning.py:65: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

Traceback (most recent call last):
  File "C:\Users\risha\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow_core\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "C:\Users\risha\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow_core\python\client\session.py", line 1348, in _run_fn
    self._extend_graph()
  File "C:\Users\risha\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow_core\python\client\session.py", line 1388, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation input_image: {{node input_image}} was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
         [[input_image]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_CIL.py", line 65, in <module>
    agent = ImitationLearning(args.city_name, args.avoid_stopping)
  File "C:\Coursera\CarlaSimulator\PythonClient\agents\imitation\imitation_learning.py", line 65, in __init__
    self._sess.run(tf.global_variables_initializer())
  File "C:\Users\risha\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "C:\Users\risha\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\risha\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "C:\Users\risha\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation input_image: node input_image (defined at C:\Users\risha\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow_core\python\framework\ops.py:1748)  was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
         [[input_image]]

it show this error

**Comment by Rookie-81** [comment]
getting the same error.
Fixed by installing cuda 10 and libcudnn 7.4 with tensorflow-gpu==1.15
